name: Handle Deno Deploy Webhook

on:
  repository_dispatch:
    types: [deno-deploy-preview]

jobs:
  update-preview-webhook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Extract Preview URL
        id: extract-url
        run: |
          # The preview URL should be in the event payload
          PREVIEW_URL="${{ github.event.client_payload.url }}"
          DEPLOYMENT_ID="${{ github.event.client_payload.deploymentId }}"
          BRANCH="${{ github.event.client_payload.branch }}"
          
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "Branch: $BRANCH"
          echo "Preview URL: $PREVIEW_URL"
          
          if [ -z "$PREVIEW_URL" ]; then
            echo "Error: No preview URL provided in webhook payload"
            exit 1
          fi
          
          # Only process non-main branches
          if [ "$BRANCH" = "main" ]; then
            echo "Skipping main branch deployment"
            exit 0
          fi
          
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
      
      - name: Update Preview Bot Webhook
        if: steps.extract-url.outputs.preview_url != ''
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PREVIEW_BOT_TOKEN: ${{ secrets.PREVIEW_BOT_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          if [ -z "$PREVIEW_BOT_TOKEN" ]; then
            echo "Error: PREVIEW_BOT_TOKEN secret is not set"
            exit 1
          fi
          
          if [ -z "$WEBHOOK_SECRET" ]; then
            echo "Error: WEBHOOK_SECRET secret is not set"
            exit 1
          fi
          
          PREVIEW_URL="${{ steps.extract-url.outputs.preview_url }}"
          
          echo "Setting webhook for preview bot to: $PREVIEW_URL"
          
          # Run the webhook update script
          deno run --allow-net --allow-env --allow-read \
            scripts/manage-webhooks.ts set preview "$PREVIEW_URL"
      
      - name: Verify Webhook
        if: steps.extract-url.outputs.preview_url != ''
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PREVIEW_BOT_TOKEN: ${{ secrets.PREVIEW_BOT_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          echo "Verifying webhook was set correctly..."
          deno run --allow-net --allow-env --allow-read \
            scripts/manage-webhooks.ts check preview
